-- THE game x team serving surface: one row per team per game. R-077.
--
-- NOTHING SAT AT THIS GRAIN BEFORE. That is why 150 measure columns across four staging
-- models — box-score advanced, team advanced, havoc and PPA — had no downstream consumer and
-- were invisible from the inside: landed, staged, and never once selected.
--
-- THE GRAIN RULE IS WHY THEY ARE HERE AND NOT ON srv_game (Marc, ratified 2026-09-02):
-- "Can't add game.team grain to a table that is at game grain." srv_game carries game-grain
-- columns and DERIVED both-team summaries; a per-team success rate is neither, so it lives
-- here. Two views, two grains, one fact family — which is the opposite of what srv_schedule
-- and srv_scoreboard were.
--
-- COVERAGE IS PARTIAL AND THE FLAGS SAY WHERE. The four sources cover 1,849 to 3,339 games
-- against 110,879 in the spine, because box scores are `recent` scope. has_box_advanced /
-- has_team_advanced / has_havoc / has_ppa distinguish "the endpoint does not cover this game"
-- from "this team recorded nothing", which a null alone cannot.
select
    a.game_team_advanced_sk,
    t.game_team_sk,
    t.game_id,
    t.season,
    t.week,
    t.season_type,
    t.game_date,
    t.team_id,
    t.team,
    -- fct_game_team carries classification but not conference; the conference is
    -- season-scoped and comes from dim_team, as it does on every other serving view.
    d.conference,
    t.classification,
    t.opponent_team_id,
    t.opponent,
    t.is_home,
    t.is_neutral_site,
    t.is_completed,
    t.points_for,
    t.points_against,
    t.margin,
    t.result,

    -- The plain box score, from fct_game_team.
    t.first_downs,
    t.total_yards,
    t.rushing_yards,
    t.passing_yards,
    t.rushing_attempts,
    t.turnovers,
    t.interceptions,
    t.fumbles_lost,
    t.third_down_conversions,
    t.third_down_attempts,
    t.fourth_down_conversions,
    t.fourth_down_attempts,
    t.penalties,
    t.penalty_yards,
    t.possession_seconds,
    t.has_box_score,

    -- Which advanced sources reached this row.
    a.has_box_advanced,
    a.has_team_advanced,
    a.has_havoc,
    a.has_ppa,

    a.plays,
    a.ppa_overall_total,
    a.ppa_overall_quarter1,
    a.ppa_overall_quarter2,
    a.ppa_overall_quarter3,
    a.ppa_overall_quarter4,
    a.ppa_passing_total,
    a.ppa_passing_quarter1,
    a.ppa_passing_quarter2,
    a.ppa_passing_quarter3,
    a.ppa_passing_quarter4,
    a.ppa_rushing_total,
    a.ppa_rushing_quarter1,
    a.ppa_rushing_quarter2,
    a.ppa_rushing_quarter3,
    a.ppa_rushing_quarter4,
    a.cumulative_ppa_overall_total,
    a.cumulative_ppa_overall_quarter1,
    a.cumulative_ppa_overall_quarter2,
    a.cumulative_ppa_overall_quarter3,
    a.cumulative_ppa_overall_quarter4,
    a.cumulative_ppa_passing_total,
    a.cumulative_ppa_passing_quarter1,
    a.cumulative_ppa_passing_quarter2,
    a.cumulative_ppa_passing_quarter3,
    a.cumulative_ppa_passing_quarter4,
    a.cumulative_ppa_rushing_total,
    a.cumulative_ppa_rushing_quarter1,
    a.cumulative_ppa_rushing_quarter2,
    a.cumulative_ppa_rushing_quarter3,
    a.cumulative_ppa_rushing_quarter4,
    a.success_rate_overall_total,
    a.success_rate_overall_quarter1,
    a.success_rate_overall_quarter2,
    a.success_rate_overall_quarter3,
    a.success_rate_overall_quarter4,
    a.success_rate_standard_downs_total,
    a.success_rate_standard_downs_quarter1,
    a.success_rate_standard_downs_quarter2,
    a.success_rate_standard_downs_quarter3,
    a.success_rate_standard_downs_quarter4,
    a.success_rate_passing_downs_total,
    a.success_rate_passing_downs_quarter1,
    a.success_rate_passing_downs_quarter2,
    a.success_rate_passing_downs_quarter3,
    a.success_rate_passing_downs_quarter4,
    a.explosiveness_total,
    a.explosiveness_quarter1,
    a.explosiveness_quarter2,
    a.explosiveness_quarter3,
    a.explosiveness_quarter4,
    a.power_success,
    a.stuff_rate,
    a.line_yards,
    a.line_yards_average,
    a.second_level_yards,
    a.second_level_yards_average,
    a.open_field_yards,
    a.open_field_yards_average,
    a.havoc_total,
    a.havoc_front_seven,
    a.havoc_db,
    a.scoring_opportunities,
    a.scoring_opportunity_points,
    a.points_per_opportunity,
    a.average_start,
    a.average_starting_predicted_points,
    a.offense_plays,
    a.offense_drives,
    a.offense_ppa,
    a.offense_total_ppa,
    a.offense_success_rate,
    a.offense_explosiveness,
    a.offense_power_success,
    a.offense_stuff_rate,
    a.offense_line_yards,
    a.offense_line_yards_total,
    a.offense_second_level_yards,
    a.offense_second_level_yards_total,
    a.offense_open_field_yards,
    a.offense_open_field_yards_total,
    a.offense_standard_downs_ppa,
    a.offense_standard_downs_success_rate,
    a.offense_standard_downs_explosiveness,
    a.offense_passing_downs_ppa,
    a.offense_passing_downs_success_rate,
    a.offense_passing_downs_explosiveness,
    a.offense_rushing_plays_ppa,
    a.offense_rushing_plays_total_ppa,
    a.offense_rushing_plays_success_rate,
    a.offense_rushing_plays_explosiveness,
    a.offense_passing_plays_ppa,
    a.offense_passing_plays_total_ppa,
    a.offense_passing_plays_success_rate,
    a.offense_passing_plays_explosiveness,
    a.defense_plays,
    a.defense_drives,
    a.defense_ppa,
    a.defense_total_ppa,
    a.defense_success_rate,
    a.defense_explosiveness,
    a.defense_power_success,
    a.defense_stuff_rate,
    a.defense_line_yards,
    a.defense_line_yards_total,
    a.defense_second_level_yards,
    a.defense_second_level_yards_total,
    a.defense_open_field_yards,
    a.defense_open_field_yards_total,
    a.defense_standard_downs_ppa,
    a.defense_standard_downs_success_rate,
    a.defense_standard_downs_explosiveness,
    a.defense_passing_downs_ppa,
    a.defense_passing_downs_success_rate,
    a.defense_passing_downs_explosiveness,
    a.defense_rushing_plays_ppa,
    a.defense_rushing_plays_total_ppa,
    a.defense_rushing_plays_success_rate,
    a.defense_rushing_plays_explosiveness,
    a.defense_passing_plays_ppa,
    a.defense_passing_plays_total_ppa,
    a.defense_passing_plays_success_rate,
    a.defense_passing_plays_explosiveness,
    a.opponent_conference,
    a.offense_total_plays,
    a.offense_total_havoc_events,
    a.offense_front_seven_havoc_events,
    a.offense_db_havoc_events,
    a.offense_havoc_rate,
    a.offense_front_seven_havoc_rate,
    a.offense_db_havoc_rate,
    a.defense_total_plays,
    a.defense_total_havoc_events,
    a.defense_front_seven_havoc_events,
    a.defense_db_havoc_events,
    a.defense_havoc_rate,
    a.defense_front_seven_havoc_rate,
    a.defense_db_havoc_rate,
    a.offense_overall,
    a.offense_passing,
    a.offense_rushing,
    a.offense_first_down,
    a.offense_second_down,
    a.offense_third_down,
    a.defense_overall,
    a.defense_passing,
    a.defense_rushing,
    a.defense_first_down,
    a.defense_second_down,
    a.defense_third_down
from {{ ref('fct_game_team') }} t
join {{ ref('fct_game_team_advanced') }} a on a.game_team_sk = t.game_team_sk
left join {{ ref('dim_team') }} d on d.season = t.season and d.team_id = t.team_id
