"""Registry of every CFBD endpoint, and how to fetch it.

Generated by hand from the CFBD OpenAPI spec (v5.24.0, 74 paths) and corrected by probing
the live API. This is the single place that decides *what exists* and *how it is
parameterized*; `src/backfill.py` executes it and knows nothing about individual endpoints.

Strategies
----------
STATIC        no parameters — one call, ever (reference data)
SEASON        one call per season: {year}
SEASON_TYPE   one call per (season, seasonType) — data that splits regular/postseason
SEASON_WEEK   one call per (season, seasonType, week) — the volume drivers
PER_GAME      one call per game id; fan-out is large, opt-in only
MANUAL        needs an argument no backfill can invent (a search term, a player id,
              a specific matchup) — reachable via `src.ingest`, never swept
LIVE          only meaningful during a game in progress; never backfilled

`include` marks membership of the default full-breadth sweep. PER_GAME/MANUAL/LIVE are
excluded by default and opted into explicitly, because their cost is a different order of
magnitude (see PER_GAME_COST_NOTE).
"""
from dataclasses import dataclass, field
from typing import Dict, List

STATIC = "static"
SEASON = "season"
SEASON_TYPE = "season_type"
SEASON_WEEK = "season_week"
PER_GAME = "per_game"
MANUAL = "manual"
LIVE = "live"

# Cadence buckets from the roadmap's M1 classification.
BUCKET_STRUCTURAL = "A"      # season-scoped structural facts
BUCKET_HISTORICAL = "B"      # immutable once the season completes
BUCKET_REVISIONIST = "C1"    # revises retroactively; re-pull whole current season
BUCKET_IMMUTABLE_WK = "C2"   # immutable once the week completes
BUCKET_PREGAME = "D"         # time-sensitive, pre-game
BUCKET_REFERENCE = "REF"     # static lookups


@dataclass(frozen=True)
class Endpoint:
    path: str
    strategy: str
    bucket: str
    include: bool = True
    note: str = ""
    # Snapshot endpoints answer differently to the *same* request over time — betting
    # lines move, pre-game win probability shifts. For these, repeat fetches with
    # identical params are the point, so `--snapshot` bypasses skip-if-present. Without
    # this the daily lines pull would be skipped from its second run onward and the
    # movement series would never accumulate.
    snapshot: bool = False
    extra: Dict[str, str] = field(default_factory=dict)

    @property
    def key(self) -> str:
        """Directory / manifest key — mirrors src.ingest."""
        return self.path.replace("/", "_")


REGISTRY: List[Endpoint] = [
    # ---- Reference: no parameters, fetch once -------------------------------------
    Endpoint("venues", STATIC, BUCKET_REFERENCE),
    Endpoint("draft/positions", STATIC, BUCKET_REFERENCE),
    Endpoint("draft/teams", STATIC, BUCKET_REFERENCE),
    Endpoint("plays/types", STATIC, BUCKET_REFERENCE),
    Endpoint("plays/stats/types", STATIC, BUCKET_REFERENCE),
    Endpoint("stats/categories", STATIC, BUCKET_REFERENCE),
    Endpoint("metrics/fg/ep", STATIC, BUCKET_REFERENCE, note="field goal expected points model"),

    # ---- Structural, season-scoped (bucket A) -------------------------------------
    Endpoint("calendar", SEASON, BUCKET_STRUCTURAL, note="drives week enumeration"),
    Endpoint("teams", SEASON, BUCKET_STRUCTURAL, note="season-correct affiliations"),
    Endpoint("teams/fbs", SEASON, BUCKET_STRUCTURAL),
    Endpoint("conferences", SEASON, BUCKET_STRUCTURAL),
    Endpoint("conferences/affiliations", SEASON, BUCKET_STRUCTURAL),
    Endpoint("conferences/changes", SEASON, BUCKET_STRUCTURAL),
    Endpoint("roster", SEASON, BUCKET_STRUCTURAL),
    Endpoint("coaches", SEASON, BUCKET_STRUCTURAL),
    Endpoint("coaches/seasons", SEASON, BUCKET_STRUCTURAL),
    # API rejects a year-only call: "coachId or team is required". A per-team fan-out
    # would work (~679 calls/season) but nothing needs it yet — reachable via src.ingest.
    Endpoint("coaches/tenures", MANUAL, BUCKET_STRUCTURAL, include=False,
             note="requires coachId or team"),

    # ---- Game results and detail (bucket B / C2) ----------------------------------
    Endpoint("games", SEASON_TYPE, BUCKET_HISTORICAL),
    Endpoint("games/media", SEASON_TYPE, BUCKET_HISTORICAL),
    Endpoint("games/weather", SEASON_TYPE, BUCKET_HISTORICAL, note="Tier 3 feature"),
    Endpoint("games/teams", SEASON_WEEK, BUCKET_IMMUTABLE_WK, note="team box scores"),
    Endpoint("games/players", SEASON_WEEK, BUCKET_IMMUTABLE_WK, note="player box scores"),
    Endpoint("drives", SEASON_TYPE, BUCKET_IMMUTABLE_WK),
    Endpoint("plays", SEASON_WEEK, BUCKET_IMMUTABLE_WK, note="highest volume: ~21k rows/week"),
    Endpoint("plays/stats", SEASON_WEEK, BUCKET_IMMUTABLE_WK, note="play-level stat lines"),

    # ---- Postseason structure ------------------------------------------------------
    Endpoint("playoffs/cfp", SEASON, BUCKET_HISTORICAL),
    Endpoint("playoffs/cfp/games", SEASON, BUCKET_HISTORICAL),
    Endpoint("playoffs/cfp/participants", SEASON, BUCKET_HISTORICAL),

    # ---- Ratings and rankings: revise retroactively (bucket C1) --------------------
    Endpoint("rankings", SEASON_TYPE, BUCKET_REVISIONIST),
    Endpoint("ratings/sp", SEASON, BUCKET_REVISIONIST),
    Endpoint("ratings/sp/conferences", SEASON, BUCKET_REVISIONIST),
    Endpoint("ratings/srs", SEASON, BUCKET_REVISIONIST),
    Endpoint("ratings/srs/expanded", SEASON, BUCKET_REVISIONIST),
    Endpoint("ratings/elo", SEASON, BUCKET_REVISIONIST),
    Endpoint("ratings/fpi", SEASON, BUCKET_REVISIONIST),
    Endpoint("ratings/core", SEASON, BUCKET_REVISIONIST),

    # ---- Team and player statistics (bucket C1) -----------------------------------
    Endpoint("records", SEASON, BUCKET_REVISIONIST),
    Endpoint("stats/season", SEASON, BUCKET_REVISIONIST),
    Endpoint("stats/season/advanced", SEASON, BUCKET_REVISIONIST),
    Endpoint("stats/game/advanced", SEASON_TYPE, BUCKET_IMMUTABLE_WK),
    Endpoint("stats/game/havoc", SEASON_TYPE, BUCKET_IMMUTABLE_WK),
    Endpoint("stats/player/season", SEASON_TYPE, BUCKET_REVISIONIST),
    Endpoint("stats/player/success", SEASON_TYPE, BUCKET_REVISIONIST),
    # Year alone is rejected: "week required when team and playerId not specified".
    Endpoint("stats/player/success/game", SEASON_WEEK, BUCKET_IMMUTABLE_WK),

    # ---- Predicted points added ----------------------------------------------------
    Endpoint("ppa/teams", SEASON, BUCKET_REVISIONIST),
    Endpoint("ppa/games", SEASON_TYPE, BUCKET_IMMUTABLE_WK),
    Endpoint("ppa/players/season", SEASON, BUCKET_REVISIONIST),
    # Year alone is rejected: "week required when team not specified".
    Endpoint("ppa/players/games", SEASON_WEEK, BUCKET_IMMUTABLE_WK),

    # ---- Adjusted (wEPA) metrics — Tier 3 feature ---------------------------------
    Endpoint("wepa/team/season", SEASON, BUCKET_REVISIONIST),
    Endpoint("wepa/players/passing", SEASON, BUCKET_REVISIONIST),
    Endpoint("wepa/players/rushing", SEASON, BUCKET_REVISIONIST),
    Endpoint("wepa/players/kicking", SEASON, BUCKET_REVISIONIST),

    # ---- Betting (bucket D) --------------------------------------------------------
    Endpoint("lines", SEASON_TYPE, BUCKET_PREGAME, snapshot=True,
             note="daily during game week; every snapshot is kept, never deduped"),
    Endpoint("teams/ats", SEASON, BUCKET_REVISIONIST, note="against the spread"),
    Endpoint("metrics/wp/pregame", SEASON_TYPE, BUCKET_PREGAME, snapshot=True),

    # ---- Player movement and recruiting -------------------------------------------
    Endpoint("player/portal", SEASON, BUCKET_STRUCTURAL, note="transfer portal"),
    Endpoint("player/returning", SEASON, BUCKET_STRUCTURAL),
    Endpoint("player/usage", SEASON, BUCKET_REVISIONIST),
    Endpoint("recruiting/players", SEASON, BUCKET_STRUCTURAL),
    Endpoint("recruiting/teams", SEASON, BUCKET_STRUCTURAL),
    Endpoint("recruiting/groups", STATIC, BUCKET_STRUCTURAL, note="all-time aggregate"),
    Endpoint("draft/picks", SEASON, BUCKET_STRUCTURAL),
    Endpoint("talent", SEASON, BUCKET_STRUCTURAL),

    # ---- Per-game fan-out: opt-in only ---------------------------------------------
    Endpoint("game/box/advanced", PER_GAME, BUCKET_IMMUTABLE_WK, include=False,
             extra={"id_param": "id"}, note="one call per game"),
    Endpoint("metrics/wp", PER_GAME, BUCKET_IMMUTABLE_WK, include=False,
             extra={"id_param": "gameId"}, note="in-game win probability, one call per game"),

    # ---- Needs an argument a sweep can't invent ------------------------------------
    Endpoint("player/search", MANUAL, BUCKET_REFERENCE, include=False, note="requires searchTerm"),
    Endpoint("player/season/overview", MANUAL, BUCKET_REFERENCE, include=False, note="requires playerId"),
    Endpoint("coaches/profile", MANUAL, BUCKET_REFERENCE, include=False, note="requires coachId"),
    Endpoint("teams/matchup", MANUAL, BUCKET_REFERENCE, include=False, note="requires team1 + team2"),
    Endpoint("ppa/predicted", MANUAL, BUCKET_REFERENCE, include=False, note="requires down + distance"),

    # ---- Live / operational: never backfilled --------------------------------------
    Endpoint("live/plays", LIVE, BUCKET_REFERENCE, include=False, note="in-progress games only"),
    Endpoint("scoreboard", LIVE, BUCKET_REFERENCE, include=False, note="live scoreboard"),
    Endpoint("info", LIVE, BUCKET_REFERENCE, include=False, note="API tier/quota, not data"),
    Endpoint("info/usage", LIVE, BUCKET_REFERENCE, include=False, note="API usage, not data"),
]

PER_GAME_COST_NOTE = """
Per-game endpoints fan out to one call per game. At ~3,800 completed games per season,
each PER_GAME endpoint costs ~3,800 calls per season — roughly 7,600 per season for both,
15,000 for 2024+2025. That fits a 75,000/month Tier 3 quota but is a different order of
magnitude from the ~600-call bulk sweep, so it is opt-in:

    python -m src.backfill --per-game --seasons 2024
""".strip()

BY_PATH: Dict[str, Endpoint] = {e.path: e for e in REGISTRY}
SWEEPABLE = [e for e in REGISTRY if e.include]


def by_strategy(strategy: str) -> List[Endpoint]:
    return [e for e in REGISTRY if e.strategy == strategy]


def resolve(names: List[str]) -> List[Endpoint]:
    """Look endpoints up by path, raising on anything unknown."""
    unknown = [n for n in names if n not in BY_PATH]
    if unknown:
        raise KeyError(f"unknown endpoint(s): {', '.join(unknown)}")
    return [BY_PATH[n] for n in names]
